name: cdk

on:
  push:
    branches:
        - develop
        - master
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    env: 
      AWS_REGION: "ap-northeast-1"
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: npm ci

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }} 
          aws-region: ${{ env.AWS_REGION }}
          
      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: |
          if [ "${GITHUB_REF##*/}" = "develop" ]; then
            npx cdk diff DevOtsukareStack
          elif [ "${GITHUB_REF##*/}" = "master" ]; then
            npx cdk diff ProdOtsukareStack

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: |
          if [ "${GITHUB_REF##*/}" = "develop" ]; then
            npx cdk deploy DevOtsukareStack --require-approval never
          elif [ "${GITHUB_REF##*/}" = "master" ]; then
            npx cdk deploy ProdOtsukareStack --require-approval never
          fi