name: cdk

on:
  push:
    branches:
        - develop
        - master
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    env: 
      AWS_REGION: "ap-northeast-1"
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: npm ci

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }} 
          aws-region: ${{ env.AWS_REGION }}
          
      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            npx cdk diff --context env=prod
          else
            npx cdk diff --context env=dev
          fi

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            npx cdk deploy --context env=prod
          else
            npx cdk deploy --context env=dev
          fi
